MedicalReportSys/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('/accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views

urlpatterns = [
 path('', views.Home.as_view(), name="home"),
 path('signup/', views.Signup.as_view(), name="signup"),
 path('docs/', views.DocsList.as_view(), name="docs"),
 path('patient/', views.PatientList.as_view(), name="patient"),
 path('patient/new/', views.PatientCreate.as_view(), name="patient_create"),
 path('patient/<int:pk>/', views.RecordDeets.as_view(), name="patient_details"),
 path('patient/<int:pk>/update/', views.RecordDeetsUpdate.as_view(), name="patient_details_update")
]

main_app/models.py
from email.policy import default
from enum import auto
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Docs(models.Model):
    firstname = models.CharField(max_length=150)
    lastname = models.CharField(max_length=150)
    specialization = models.CharField(max_length=150)
    email = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.lastname

class Patient(models.Model):
    firstname = models.CharField(max_length=150)
    lastname = models.CharField(max_length=150)
    ethnicity = models.CharField(max_length=150)
    dob = models.DateField()

    def __str__(self):
        return self.lastname

class Records(models.Model):
    history = models.CharField(max_length=200, null=True)
    allegries = models.CharField(max_length=150, null=True)
    condition = models.CharField(max_length=200, null=True)
    labresults = models.CharField(max_length=200, null=True)
    notes = models.CharField(max_length=300, null=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    docs = models.ForeignKey(Docs, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.patient.lastname

main_app/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.http import HttpResponse
from django.views.generic.base import TemplateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import Docs, Patient, Records
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse

# Create your views here.
class Home(View):
    def get(self, request):
        return HttpResponse("Medical Report System")

class Home(TemplateView):
    template_name = "home.html"

class Signup(View):
    def get(self, request):
        form = UserCreationForm()
        context = {'form': form}
        return render(request, "registration/signup.html", context)

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("docs")
        else:
            context = {"form": form}
            return render(request, "registration/signup.html", context)

# class Docs(View):
#     def get(self, request):
#         return HttpResponse("This is the page for Docs")

@method_decorator(login_required, name='dispatch')
class DocsList(TemplateView):
    model = Docs
    template_name = "docs.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["docs"] = Docs.objects.filter(user=self.request.user)
        return context

# class Patient(View):
#     def get(self, request):
#         return HttpResponse("patient")

class PatientList(TemplateView):
    model = Patient
    template_name = "patient.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['patient'] = Patient.objects.all()
        searchName = self.request.GET.get("lastname")
        if searchName != None:
            context["patient"] = Patient.objects.filter(lastname__icontains=searchName)
        else:
            context["patient"] = Patient.objects.all()
        return context

class PatientCreate(CreateView):
    model = Patient
    fields = ['firstname', 'lastname', 'ethnicity', 'dob']
    template_name = "patient_create.html"
    def form_valid(self, form):
        return super(PatientCreate, self).form_valid(form)
    success_url = "/patient/"

class RecordDeets(TemplateView):
    model = Patient
    template_name = "patient_details.html"

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["patient"] = Patient.objects.get(pk=context['pk'])
        tab = self.request.GET.get('tab')
        context['tab'] = tab
        print(context)
        return context

class RecordDeetsUpdate(View):

    def post(self, request, pk):
        field = request.POST.get("field")
        print(field)
        fieldValue = request.POST.get("fieldValue")
        print(fieldValue)
        patient = Patient.objects.get(pk=pk)
        print(patient)
        if field == 'history':
            Records.objects.create(history=fieldValue, patient=patient)
        elif field == 'allegries':
            Records.objects.create(allegries=fieldValue, patient=patient)
        elif field == 'condtion':
            Records.objects.create(condition=fieldValue, patient=patient)
        elif field == 'labresults':
            Records.objects.create(labresults=fieldValue, patient=patient)
        elif field == 'notes':
            Records.objects.create(notes=fieldValue, patient=patient)
        return redirect('patient_details', pk=pk)

main_app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="shortcut icon" href="../images/fav_icon.png" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <!-- Bulma Version 0.9.0-->
    <link rel="stylesheet" href="https://unpkg.com/bulma@0.9.0/css/bulma.min.css" />
    <style type="text/css">
      html,
      body {
          font-family: 'Open Sans';
      }

      img {
          padding: 5px;
          border: 1px solid #ccc;
      }
  </style>

    <title>{% block title %} {% endblock %} </title>
</head>
<body>
  <div class="container p-3 my-3">
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-expand-md navbar-light " style="background-color: #f0f5f5">
          <a class="navbar-item" href="{% url 'home' %}">Home</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <div class="navbar-menu navbar-end">
                {% if user.is_authenticated %}
                <div class="navbar-menu navbar-end">
                        <span class="navbar-item">Welcome: {{user.username}}</span>
                        <a class="navbar-item" href="{% url 'patient' %}">Patients</a>
                        <a class="navbar-item" href="{% url 'docs' %}">Profile</a>
                        <a class="navbar-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                {% else %}
                    <div class="navbar-menu navbar-end">
                        <a class="navbar-item" href="{% url 'login' %}">Log In</a>
                        <a class="navbar-item" href="{% url 'signup' %}">Signup</a>
                    </div>
                {% endif %}
            </div>
            </div>
          </nav>
          {% block content %}{% endblock %}
      </div>
    </div>
  </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

main_app/templates/docs.html
{% extends 'base.html' %} 
{% block title %} Profile {% endblock %}
<h1>This is the profile page for {{user.username}}</h1>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <section class="hero is-fullheight is-default is-bold">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="columns is-vcentered">
                    <div class="column is-5">
                        <figure class="image is-4by3">
                            <img src="https://picsum.photos/800/600/?random" alt="Description">
                        </figure>
                    </div>
                    <div class="column is-6 is-offset-1">
                        <h1 class="title is-2">
                            Hazel is SuperHero
                        </h1>
                        <h2 class="subtitle is-4">
                            All Docs are the Heros
                        </h2>
                        <br>
                        <p class="has-text-centered">
                            <a class="button is-medium is-info is-outlined">
                                Learn more
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="hero-foot">
            <div class="container">
                <div class="tabs is-centered">
                    <ul>
                        <li><a>Hazel the Boss</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

main_app/templates/patient.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row" style="gap: 20px; margin-top: 20px;">
        <a class="button is-dark col-md-2" href="{% url 'patient_create' %}">Add Patient</a>
        <form class="row" style="gap: 20px;" method="get">
            <div class="control">
                <input class="input col-sm-" style="max-width: 150px;" type="text" name="lastname" placeholder="lastname" />
            </div>
            <div class="control">
                <input class="button is-dark col-sm-" type="submit" value="Search" />
            </div>
            <a class="button is-dark col-sm-" href="{% url 'patient' %}">Clear Search</a>
        </form>
    </div>
    <div class="table" style="margin-top: 20px;">
        <table>
            <thead>
                <tr>
                    <th>Patient Name</th>
                    <th>Race</th>
                    <th>DOB</th>
                </tr>
            </thead>
            <tbody>
                {% for p in patient %}
                <tr>
                    <td> <a href="{% url 'patient_details' p.pk%}">{{p.firstname}} {{p.lastname}}</td></a>
                    <td>{{p.ethnicity}}</td>
                    <td>{{p.dob}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

main_app/templates/patient_create.html
{% extends 'base.html' %} 
{% block content %}
<h1>Add a Patient</h1>

<form method="post">

  {% csrf_token %} 

  {{form.as_p}} 

  <input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/patient_details.html
{% extends "base.html" %}
{% block content %} 
    {{ patient }}
    <h5>{{patient.lastname}}, {{patient.firstname}}</h5>
    <ul class="tabs" data-tabs="tabs">
        <li class="active"><a href="?tab=history">History</a></li>
        <li><a href="?tab=allegries">Allegries</a></li>
        <li><a href="?tab=condition">Condition</a></li>
        <li><a href="?tab=labresults">Lab Results</a></li>
        <li><a href="?tab=notes">Notes</a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        {% for record in patient.records_set.all %}
        {% if tab == "history" %}
        <div class="active" id="history">
            <li>{{record.history}}</li>
        </div>
        {% elif tab == "allegries" %}
        <div id="allergies">
            <li>{{record.allegries}}</li>
        </div>
        {% elif tab == "condition" %}
        <div id="condition">
            <li>{{record.condition}}</li>
        </div>
        {% elif tab == "labresults" %}
        <div id="labresults">
            <li>{{record.labresults}}</li>
        </div>
        {% elif tab == "notes" %}
        <div id="notes">
            <li>{{record.notes}}</li>
        </div>
        {% endif %}

        {% endfor %}
        <form action="{% url 'patient_details_update' patient.pk %}"method="post">
            {% csrf_token %} 
            <label for="field">Choose a field:</label>
            <select id="field" name="field">
                <option value="history">History</option>
                <option value="allegries">Allegries</option>
                <option value="condition">Condition</option>
                <option value="labresults">Lab Results</option>
                <option value="notes">Notes</option>
            </select>
            <label for="fieldValue">Enter text:</label>
            <input type="text" name="fieldValue">
            <button class="button is-dark">Submit</button>
        </form>
    </div>
{% endblock %}